[[section-introduction-and-goals]]
== Introducción y metas

Una empresa de venta de productos busca originar un sistema de venta online denominado DeDe (Decentralized Delivery).
Estará centrada en la venta de productos informáticos de diferentes ámbitos (como ratones, teclados...).
Este sistema busca priorizar la privacidad de los clientes a través de los principios SOLID.
El sistema obtendrá la información de los clientes de los pods de los usuarios siempre que éstos den los permisos necesarios al sistema de venta.
Se distinguirá entre usuarios normales y adminstradores. Éstos pueden, además de acceder a la tienda, crear, modificar y eliminar los productos de la base de datos.
Los usuarios eligirán los productos que formarán parte de su carro de compra. Cada usuario tiene su propio carro individual.


=== Información general de los requisitos

A continuación se muestran los requisitos que se puedes encontrar en nuestra aplicación. Se dividen en obligatorios y opcionales

.Requisitos obligatorios

* El sistema recreará un sistema de compra online donde los usuarios podrán elegir y solicitar productos a comprar.
* Una vez que el usuario escoja los productos a llevar, el sistema calculará los costes de envío mirando la dirección deseada del usuario en su pod y estableciendo los costes de acuerdo a la distancia del centro de distribución a dicha dirección.
* Se mostrarán los costes finales de los productos a comprar y, una vez que el usuario tome la decisión de comprarlos, registrará el evento que indicará que la venta ha sido completada y se pasará al envío.
* Los usuarios podrán visualizar los pedidos realizados
* Se construirá la aplicación usando el framework React y Typescript.
* El producto acabado tiene que ser accesible y estar desplegado utilizando un sistema de integración continua y un servicio de hosting.

.Requisitos opcionales

* Rol de gestores que puedan realizar diferentes acciones como gestión de inventario, cambios de precios, quitar ítems del catálogo, etc.
* Se añade tambien una vista en el que el administrador pueda ver todos los pedidos que se han realizado. 
* Un usuario puede actuzalziar el nombre de este dentro de la aplicación


=== Objetivos de calidad


[options="header",cols="1,2,2"]
|===
|Objetivos de calidad|Motivación|Importancia
| Eficiencia | Buscamos en la medida de lo posible mejorar los tiempos de respuesta | Media
| Seguridad | El usuario debe tener la certeza de que su información personal esté segura para ganar su confianza | Alta
| Robustez | Se ha de manejar correctamente las excepciones para evitar que el usuario tenga una experiencia desagradable usando la aplicación | Alta
| Privacidad | Solamente el usuario debería tener acceso a su información privada, sin que haya terceras partes implicadas | Alta
| Transparencia | Todo lo que se haga en el proyecto permanecerá en un repositorio público para que otra gente lo pueda tener como referencia | Alta
| Comodidad | La aplicación ha de ser fácil de manejar para gente no experimentada | Alta
|===


=== Stakeholders

[options="header",cols="1,2"]
|===
|Rol/Nombre|Expectations
| Equipo de desarrollo | Aprender a trabajar en equipo con gente que no conocen y familiarizarse con las tecnologías solicitadas en el curso
| Empresa de venta de productos (cliente) | Una aplicación funcional que satisfaga los requisitos solicitados, especialmente aquellos relacionados con la seguridad
| Cliente | Poder entrar a la aplicación para realizar las compras que desean de forma segura y cómoda. Introducirán sus productos en un carro de la compra.
| Administrador | Tener el control de una aplicación robusta y eficiente que incluya la posiblidad de crear, modificar, eliminar productos, ver los usuarios y pedidos
| Inrupt/Empathy | Entidades colaboradoras del concurso SOLID en el que se puede presentar el proyecto desarrollado durante el curso
|===



