[[section-introduction-and-goals]]
== Introducción y metas

Una empresa de venta de productos busca originar un sistema de venta online denominado DeDe (Decentralized Delivery).
Estará centrada en la venta de productos informáticos de diferentes ámbitos (como ratones, teclados...).
Este sistema busca priorizar la privacidad de los clientes a través de los principios SOLID.
El sistema obtendrá la información de los clientes de los pods de los usuarios siempre que éstos den los permisos necesarios al sistema de venta.



=== Información general de los requisitos


.Requisitos obligatorios

* El sistema recreará un sistema de compra online donde los usuarios podrán elegir y solicitar productos a comprar.
* Una vez que el usuario escoja los productos a llevar, el sistema calculará los costes de envío mirando la dirección deseada del usuario en su pod y estableciendo los costes de acuerdo a la distancia del centro de distribución a dicha dirección.
* Se mostrarán los costes finales de los productos a comprar y, una vez que el usuario tome la decisión de comprarlos, registrará el evento que indicará que la venta ha sido completada y se pasará al envío.
* Los usuarios podrán visualizar los pedidos realizados
* Se construirá la aplicación usando el framework React y Typescript.
* El producto acabado tiene que ser accesible y estar desplegado utilizando un sistema de integración continua y un servicio de hosting.

.Requisitos opcionales

* Los usuarios pueden tener más de una dirección de envío en sus pods (por ejemplo, en sus casas, universidad, …)
* Poner una estimación del tiempo en que la persona estará en un sitio y limitar algunas direcciones de ser usadas en la entrega fuera de esos horarios.
* Crear estaciones de recogida que algunos portadores emplearán. La estación de recogida se puede calcular de forma dinámica basándose en la dirección de la persona o en una posición que pille de camino al receptor.
* Se pueden usar APIs externas de diferentes portadores, para que los usuarios puedan establecer con cuál de los portadores desean realizar el pedido.
* Hacer que algunos usuarios con privilegios de administrador puedan ver estadísticas de productos solicitados y monitorizar el estado de los pedidos.
* Realizar el producto tanto en una aplicación web como una aplicación de móvil.
* Crear un emulador del sistema de envío que pueda notificar a los usuarios cuando los productos hayan llegado a su destino y poder seguir el proceso de envío.
* Tener diferentes roles como clientes o gestores que puedan realizar diferentes acciones como gestión de inventario, cambios de precios, quitar ítems del catálogo, etc.
* Incluir la posibilidad de que haya varios centros de distribución o almacenes en los que se encuentren almacenados los productos.
* Que los usuarios puedan añadir o actualizar la información de sus direcciones en sus pods a través de la aplicación.
* Permitir a los usuarios dar realimentación sobre su experiencia como puntuaciones y revisiones a los productos o los centros de distribución.
* Se deja abierta la opción de emplear más de una tecnología de despliegue.


=== Objetivos de calidad


[options="header",cols="1,2,2"]
|===
|Objetivos de calidad|Motivación|Importancia
| Eficiencia | La aplicación utilizará la menor cantidad de recursos posibles para  generar las respuestas a las peticiones, mejorando así los tiempos de respuesta | Media
| Seguridad | El usuario debe tener la certeza de que su información personal esté segura para ganar su confianza | Alta
| Robustez | Se ha de manejar correctamente las excepciones para evitar que el usuario tenga una experiencia desagradable usando la aplicación | Media
| Privacidad | Solamente el usuario debería tener acceso a su información privada, sin que haya terceras partes implicadas | Alta
| Portabilidad | La aplicación ha de poder ejecutarse en diferentes plataformas o entornos integrados | Baja
| Comodidad | La aplicación ha de ser fácil de manejar para gente no experimentada | Alta
|===


=== Stakeholders

[options="header",cols="1,2"]
|===
|Rol/Nombre|Expectations
| Equipo de desarrollo | Aprender a trabajar en equipo con gente que no conocen y familiarizarse con las tecnologías solicitadas en el curso
| Empresa de venta de productos (cliente) | Una aplicación funcional que satisfaga los requisitos solicitados, especialmente aquellos relacionados con la seguridad
| Cliente | Poder entrar a la aplicación para realizar las compras que desean de forma segura y cómoda
| Administrador | Tener el control de una aplicación robusta y eficiente con la que poder satisfacer las necesidades de los usuarios
|===



