[[section-solution-strategy]]
== Soluciones de estretegia

=== Restricciones tecnologicas
- React: libreria de acceso libre que en este caso se utilizara con TypeScript diseñada para que el diseño de las interfaces web sean más fáciles. 
- Pod Solid: almacenamiento de la inforamción personal de cada usuario. 
- TypeScript: lenguaje de programación con el que está desarrollada la aplicación. 

=== Deciones tecnologicas
- Node.js: entorno en tiempo de ejecución multiplataforma, de código abierto, para la capa del servidor basado en el lenguaje de programación JavaScript, asíncrono, con E/S de datos en una arquitectura orientada a eventos y basado en el motor V8 de Google.
- MongoDB: sistema de base de datos NoSQL orientado a documentos. Además MongoDB es de código abierto por lo que se permite una mayor libertad de creación de documentos
- MUI: Libreria de libre acceso para construir los diferentes componentes que utiliza la aplicación. La mayoria de componentes que se utilizan en nuestra aplicación son de esta librería y son personalizados según se necesita el formato de este.
- Docker: Automatizacion del despligue medainte contenedores, se han creado dos contenedores, uno para la parte de 'front-end' y otro para 'back-end'
- AWS: Depligue de la página.
- EasyPost: API que calcula el precio de envío en funcion de una dirección
- PostImages: API utilizada para poder utilizar las imagenes en nuestra aplicación.
- SuperTest y Jest: Utilizado para poder realziar las diferentes pruebas.

=== Decisiones de organización
 * Revisiones y reuniones acordadas con antelación se realizarán a través de la aplicación Microsoft Teams.
 * Mensajería instantanea para acordar aquellas reuniones que se realicen de forma online, también para avisar de cambios pequeños.
 * GitHub para reflejar el trabajo que se esta realizando de varias formas: 
 ** Rama individual para cada uno, donde deberá realizar su trabajo. Rama Developer donde se iran incluyendo los cambios de todos los miembros para despues poder realizar de una manera más sencilla los cambios a master.
 ** Uso de wikis para recoger todo lo acordado en las reuniones y  del registro arquitéctonico.
 ** Uso de issues para indicar las cosas que tiene que realizar cada miembro del equipo. 
 ** Uso de Actions para commprobar el correcto funcionamiento de la aplicación
 ** Uso de Tableros para controlar como esta siendo el desarrollo del trabajo, se dividieron en 4 tableros:
 *** FrontEnd
 *** BackEnd
 *** Documentación
 *** Despliegue
