[[section-solution-strategy]]
== Soluciones de estretegia

=== Restricciones tecnologicas
- React: libreria de acceso libre que en este caso se utilizara con TypeScript diseñada para que el diseño de las interfaces web sean más fáciles. 
- Pod Solid: almacenamiento de la inforamción personal de cada usuario. 
- TypeScript, lenguaje de programación con el que está desarrollada la aplicación. 

=== Deciones tecnologicas
- Node.js: entorno en tiempo de ejecución multiplataforma, de código abierto, para la capa del servidor basado en el lenguaje de programación JavaScript, asíncrono, con E/S de datos en una arquitectura orientada a eventos y basado en el motor V8 de Google.
- MongoDB: sistema de base de datos NoSQL orientado a documentos. Además MongoDB es de  código abierto

=== Como alcanzar los objetivos de calidad
[options="header",cols="1,2"]
|===
|Objetivos de calidad| Solución
| Eficiencia | El acceso al pod del usuario se hará las minimas veces posibles. Realización de pruebas para comprobar como de rápido responde la aplicación
| Privacidad | Utilización de un POD por cada usuario, donde el usuario deberá dar permiso a la web para utilizar sus datos. 
| Usabilidad | La página tendrá un aspecto parecido al resto de aplicaciones que existen sobre tiendas online.
|=== 

=== Descomposición de alto nivel del sistema
Todavía no se ha decidido como va a estar.

=== Decisiones de organización
 * Revisiones y reuniones acordadas con antelación se realizarán a través de la aplicación Microsoft Teams.
 * Mensajería instantanea para acordar aquellas reuniones que se realicen de forma online, también para avisar de cambios pequeños.
 * GitHub para reflejar el trabajo que se esta realizando de varias formas: 
 ** Rama individual para cada uno, donde deberá realizar su trabajo.
 ** Uso de wikis para recoger todo lo acordado en las reuniones.
 ** Uso de issues para indicar las cosas que tiene que realizar cada miembro del equipo. 
 ** Uso de Actions para commprobar el correcto funcionamiento de la aplicación

