[[section-building-block-view]]


== Building Block View

[role="arc42help"]

=== Descripción del sistema en caja blanca
El siguiente diagrama permite mostrar las distitnas capas de la aplicación y la manera en la que el usuario interactúa con ella:

image:05_building_block_whitebox_level_1["Building block view - Whitebox Overall System"]

En el diagrama se muestra la forma de interactuar tanto del administrador, como del usuario, con el sistema. Estos dos tipos de usuarios
tendrán dos vistas distintas, teniendo así distintas operaciones disponible a realizar, esta distinción en la aplicación se explicará en el 
nivel 2.

Se representa la aplicación DeDe en un diagrama de caja blanca con un modelo del tipo MVC, en el que cada parte de dicho modelo se representa con una
caja negra.

*Descripciones de las cajas negras del diagrama*

|===
|Nombre|Responsabilidad
|Modelo|Gestiona la persistencia de datos, almacenándolos en la base de datos y recuperándolos cuando se necesitan. Se define el modelo de datos.
|Vista|Capa con la que interacciona usuario y administrador, además representa los datos del modelo.
|Controlador|Intermediario entre la capa de modelo y la de vista, gestiona las interacciones entre ambos.
|===


