[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****

=== <Runtime Scenario 1>


* _<insert runtime diagram or textual description of the scenario>_
* _<insert description of the notable aspects of the interactions between the
building block instances depicted in this diagram.>_

It is possible to use a sequence diagram:

[plantuml,"Sequence diagram",png]
----
actor Alice
actor Bob
database Pod as "Bob's Pod"
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response
Alice  --> Pod: Store route
Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
----

=== Añadir productos

El administrador rellenará un formulario con los detalles del producto que se mandará a un controlador. El controlador se encargará de enviar la petición al repositorio para que se almacene en la base de datos.

----
actor Administrador
actor ProductoController
actor ProductoRepository
database Pod as "Base de datos"
Administrador --> ProductoController: Manda una solicitud POST
ProductoController --> ProductoRepository: Petición de crear el producto
ProductoRepository --> Base de datos: Crea y almacena el producto 
ProductoRepository --> ProductoController: Informa del éxito de la operación
Administrador <-- ProductoController: Da el visto bueno con un mensaje 
----


=== Eliminar productos

El administrador rellenará un formulario con los detalles del producto a borrar.El controlador le pasará la información necesaria al modelo para que éste pueda eliminar el producto de la base de datos. 

----
actor Administrador
actor ProductoController
actor ProductoRepository
database Pod as "Base de datos"
Administrador --> ProductoController: Manda una solicitud POST
ProductoController --> ProductoRepository: Petición de eliminar el producto
ProductoRepository --> Base de datos: Elimina el producto de la base de datos
ProductoRepository --> ProductoController: Informa del éxito de la operación
Administrador <-- ProductoController: Da el visto bueno con un mensaje 
----

