name: CI for ASW2122

on:
  release:
    types: [published]

jobs:
   unit-test-webapp:
     runs-on: ubuntu-latest
     defaults:
       run:
         working-directory: webapp
     steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v2
       with:
         node-version: 16
     - run: npm ci
     - run: npm test
     - uses: codecov/codecov-action@v2
  unit-test-restapi:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: restapi
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: npm ci
    - run: npm test
    - uses: codecov/codecov-action@v2
#  e2e-tests:
#    needs: [unit-test-webapp, unit-test-restapi]
#   runs-on: ubuntu-latest
#    steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v2
#       with:
#         node-version: 16
#     - run: npm --prefix webapp install
#     - run: npm --prefix restapi install
#     - run: npm --prefix webapp run build
#     - run: npm --prefix webapp run test:e2e
  docker-push-webapp:
    name: Push webapp Docker Image to GitHub Packages
    env:
      REACT_APP_API_URI: http://${{ secrets.DEPLOY_HOST }}:5000
    runs-on: ubuntu-latest
    needs: [unit-test-webapp]
    steps:
    - uses: actions/checkout@v2
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@3.04
      with:
          name: arquisoft/dede_es2c/webapp
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PUSH_TOKEN }}
          registry: ghcr.io
          workdir: webapp
          buildargs: REACT_APP_API_URI
  docker-push-restapi:
    name: Push restapi Docker Image to GitHub Packages
    env:
      DATABASE_USER: ${{ secrets.DB_USER }}
      DATABASE_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DATABASE_NAME: ${{ secrets.DB_NAME }}
      JWT_TOKEN: ${{ secrets.TOKEN }}
    runs-on: ubuntu-latest
    needs: [unit-test-restapi]
    steps:
    - uses: actions/checkout@v2
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@3.04
      with:
          name: arquisoft/dede_es2c/restapi
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PUSH_TOKEN }}
          registry: ghcr.io
          workdir: restapi
          buildargs: DATABASE_USER,DATABASE_PASSWORD,DATABASE_NAME,JWT_TOKEN
  deploy:
    name: Deploy over SSH
    runs-on: ubuntu-latest
    needs: [docker-push-restapi,docker-push-webapp]
    steps:
    - name: Deploy over SSH
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        user: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        command: |
          wget https://raw.githubusercontent.com/Arquisoft/dede_es2c/Dario/docker-compose-deploy.yaml -O docker-compose.yml
          docker-compose stop
          docker-compose rm -f
          docker-compose pull   
          docker-compose up -d
